// Generated by Amplify at build time; declared here only so the
// standalone `tsc -p amplify/tsconfig.json` check (outside the ampx
// pipeline) can resolve it. The real module is substituted by Amplify's
// build tooling at deploy time.
declare module '$amplify/env/send-escalation-push' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const env: any;
}
